PizzariaRoma/Models/Pizza.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Profile;

namespace PizzariaRoma.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        [Required, MaxLength(45)]
        public string Name { get; set; }
        [Required, MaxLength(250)]
        public string Description { get; set; }
        public decimal Price { get; set; }
        [Column(TypeName = "image")]
        public byte[] Image { get; set; }

        [Required]
        public Ingredient Ingredient { get; set; }
        public int IngredientId { get; set; }   

    }
}

PizzariaRoma/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PizzariaRoma.Models;

namespace PizzariaRoma.Controllers
{
    public class PizzaController : Controller
    {
        private ApplicationDbContext _context;

        public PizzaController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: Pizza
        public ActionResult Index()
        {
            var pizzas = _context.Pizzas.Include(p => p.Id).ToList();

            if (pizzas == null)
                return HttpNotFound();

            return View(pizzas);
        }

        public ActionResult Detail(int id)
        {

            var pizza = _context.Pizzas.Include(p => p.Id).FirstOrDefault(m => m.Id == id);

            if (pizza == null)
                return HttpNotFound();

            return View(pizza);

        }

    }
}

PizzariaRoma/Views/Pizza/Detail.cshtml
@model PizzariaRoma.Models.Pizza

<!DOCTYPE html>

<html>
<head>
    <title>Pizza detail</title>
</head>
<body>
    <div>
     
        <h2>@Model.Name</h2>

        <ul>
            <li>
                Description: @Model.Description   
            </li>
            <li>
                Price: @Model.Price.ToString()
            </li>
            <li>
                Image: @Model.Image
            </li>
    
            <li>
               Ingredients: @Model.Ingredient.Name.ToList()   
            </li>
    
        </ul>
    </div>
</body>
</html>

PizzariaRoma/Views/Pizza/Index.cshtml
@model List<PizzariaRoma.Models.Pizza>

<!DOCTYPE html>

<html>
<head>
    <title>Pizza's</title>
</head>
<body>
<div>
      @foreach (var pizza in Model)
      {
          <tr>
              <td> @Html.ActionLink(pizza.Name, "Detail", "Pizza", new {id = pizza.Id}, null) </td>
              <td> @pizza.Ingredient.Name</td>
          </tr>
      }
</div>
</body>
</html>